## Experiment-1
#### Aim: Introduction to python, numpy
##### Bhuvnesh Sanathra IT-123

In [1]:
print("Bhuvnesh R Sanathra")

Bhuvnesh R Sanathra


In [3]:
a=10
print("Hello: "+ str(a))

Hello: 10


In [4]:
a=10
print(a**2)

100


In [5]:
print(f"Bhuvnesh {a}")

Bhuvnesh 10


In [9]:
a=10
b=20.5
c=True

print(f"Value of A: {a},\nValue of B: {b},\nValue of C: {c}.")

Value of A: 10,
Value of B: 20.5,
Value of C: True.


In [12]:
print(f"Type of A: {type(a)},\nType of B: {type(b)},\nType of C: {type(c)}.")

Type of A: <class 'int'>,
Type of B: <class 'float'>,
Type of C: <class 'bool'>.


# Mathematical Operation 

In [17]:
# ESC M SHIFT+ENTER -> For Heading

In [20]:
a=10
b=20

print(a+b)
print(a-b)
print(a*b)
print(a/b)  # /  With fraction point
print(a//b) # // Remove Floating Point

30
-10
200
0.5
0


In [26]:
a=10
b=20
print(f"Value of A: {a} and B: {b}")
print(f"a>b: {a>b}")
print(f"a<b: {a<b}")
print(f"a==b: {a==b}")
print(f"a!=b: {a!=b}")
print(f"a&b: {a&b}")

Value of A: 10 and B: 20
a>b: False
a<b: True
a==b: False
a!=b: True
a&b: 0


In [32]:
a=20
b=30

print(f"The value of A: {a} and B: {b}")
if(a>b):
    print(f"A: {a}")
else:
    print(f"B: {b}")

The value of A: 20 and B: 30
B: 30


## Looping Statements
### For Loop

In [43]:
a=10
for i in range(a):
    print(i+1)

1
2
3
4
5
6
7
8
9
10


### While Loop

In [44]:
# While Loop
i=1
while i<=a:
    print(i)
    i+=1 # i++ is not working in Python

1
2
3
4
5
6
7
8
9
10


## Composite DataType in Python

In [84]:
# Multiple data value we can store in one variable
# List, Tuple And Dictionary
# List: is immutable => []
# Tuple: is Mutable => ()
# Dictionary: Key Value => {key:value}
# How to access the data using Index Value list[0]

list =['Bhuvnesh','R','Sanathra','1','2','3','4']
tuple=('Bhuvnesh','R','Sanathra')
dictionary={'Name':'Bhuvnesh R Sanathra','Desegnition':'Student'}

print(f"This is from List: {list}")
print(f"This is from tuple: {tuple}")
print(f"This is from dictionary: {dictionary}")
print(f"This is from dictionary['Name']: {dictionary['Name']}")

# Operations on Data
# Array Slicing list[a:b:c] a-> Start Index b-> Last Index c-> Step Size
print(f"This is from list[2:7:2]: {list[2:7:2]}")
print(f"This is from list[-1::-1] Reverse of List: {list[-1::-1]}")

This is from List: ['Bhuvnesh', 'R', 'Sanathra', '1', '2', '3', '4']
This is from tuple: ('Bhuvnesh', 'R', 'Sanathra')
This is from dictionary: {'Name': 'Bhuvnesh R Sanathra', 'Desegnition': 'Student'}
This is from dictionary['Name']: Bhuvnesh R Sanathra
This is from list[2:7:2]: ['Sanathra', '2', '4']
This is from list[-1::-1] Reverse of List: ['4', '3', '2', '1', 'Sanathra', 'R', 'Bhuvnesh']


## Function in Python
### VoteCalculator Function

In [87]:
def voteCalculator(age):
    if(age>=18):
        return True
    else:
        return False

print(voteCalculator(18));

True


### Factorial Function

In [110]:
def factorial(fact):
    if(fact <= 1):
        return 1
    else:
        return fact*factorial(fact-1)
    
print(f"Factorial of 5: {factorial(5)}\n")
print("Factorial using Looping\n------------------")

for i in range(10):
    print(f"Factorial of {i}'th Digit: {factorial(i)}")

Factorial of 5: 120

Factorial using Looping
------------------
Factorial of 0'th Digit: 1
Factorial of 1'th Digit: 1
Factorial of 2'th Digit: 2
Factorial of 3'th Digit: 6
Factorial of 4'th Digit: 24
Factorial of 5'th Digit: 120
Factorial of 6'th Digit: 720
Factorial of 7'th Digit: 5040
Factorial of 8'th Digit: 40320
Factorial of 9'th Digit: 362880


### Fibonacci Series

In [117]:
def fibonacci(fib):
    if(fib==0 or fib==1):
        return fib
    else:
        return fibonacci(fib-1)+fibonacci(fib-2)

print(f"Fibonacci of 5: {fibonacci(5)}\n")

a=int(input("Enter Number: "))

print("\nFibonacci using Looping\n------------------")
for i in range(10):
    print(f"Fibonacci of {i}'th Digit: {fibonacci(i)}")

Fibonacci of 5: 5

Enter Number: 10

Fibonacci using Looping
------------------
Fibonacci of 0'th Digit: 0
Fibonacci of 1'th Digit: 1
Fibonacci of 2'th Digit: 1
Fibonacci of 3'th Digit: 2
Fibonacci of 4'th Digit: 3
Fibonacci of 5'th Digit: 5
Fibonacci of 6'th Digit: 8
Fibonacci of 7'th Digit: 13
Fibonacci of 8'th Digit: 21
Fibonacci of 9'th Digit: 34


# PIP
### PIP Manual

In [120]:
pip --help



Usage:   
  C:\Users\user1\anaconda3\python.exe -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
 

### Python Version

In [133]:
# !pip -> It will install the packages in base environment
# pip  -> it will install the packages in current kernel which is running
!pip --version 

pip 21.0.1 from C:\Users\user1\anaconda3\lib\site-packages\pip (python 3.8)



In [131]:
pip --version

pip 21.0.1 from C:\Users\user1\anaconda3\lib\site-packages\pip (python 3.8)

Note: you may need to restart the kernel to use updated packages.


# Numpy

In [134]:
# It is Numerical Python
# pip uninstall package
# pip install package

In [137]:
pip install numpy

### One-dimensional Array

In [140]:
# Given name to Numpy -> np
import numpy as np

In [152]:
# it will store the array
a=np.array(['Bhuvnesh','R','Sanathra'])
print(f'The A using numpy        : {a}')
print(f'The a[:] using numpy     : {a[:]}')
print(f'The a[0:3] using numpy   : {a[0:3]}')
print(f'The a[-1::-1] using numpy: {a[-1::-1]}')

The A using numpy        : ['Bhuvnesh' 'R' 'Sanathra']
The a[:] using numpy     : ['Bhuvnesh' 'R' 'Sanathra']
The a[0:3] using numpy   : ['Bhuvnesh' 'R' 'Sanathra']
The a[-1::-1] using numpy: ['Sanathra' 'R' 'Bhuvnesh']


### Multi-dimensional Array

In [176]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'The B using numpy        : \n\n{b}\n')
print(f'The B[0,2] using numpy   : {b[0,2]}\n')
print(f'The b[:] using numpy     : \n\n{b[:]}\n')
print(f'The b[0:1] using numpy   : \n\n{b[0:1]}\n')
print(f'The b[-1::-1] using numpy: \n\n{b[-1::-1]}\n')

The B using numpy        : 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The B[0,2] using numpy   : 3

The b[:] using numpy     : 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The b[0:1] using numpy   : 

[[1 2 3]]

The b[-1::-1] using numpy: 

[[7 8 9]
 [4 5 6]
 [1 2 3]]



## Functions given to us For One Dimensional

In [175]:

print(f'The a[0] using numpy    :{a[0]}')
print(f'The a[2:] using numpy   :{a[2:]}')
print(f'The a[:3] using numpy   :{a[:3]}')
print(f'The a[-1] using numpy   :{a[-1]}')
print(f'The a[-3:] using numpy  :{a[-3:]}')
print(f'The a[1:2] using numpy  :{a[1:2]}')

The a[0] using numpy    :Bhuvnesh
The a[2:] using numpy   :['Sanathra']
The a[:3] using numpy   :['Bhuvnesh' 'R' 'Sanathra']
The a[-1] using numpy   :Sanathra
The a[-3:] using numpy  :['Bhuvnesh' 'R' 'Sanathra']
The a[1:2] using numpy  :['R']


## Functions given to us For Two-Dimensional

In [178]:
print(f'The b[0,2] using numpy   : \n\n{b[0,2]}\n')
print(f'The b[0,:] using numpy   : \n\n{b[0,:]}\n')
print(f'The b[1,:] using numpy   : \n\n{b[1,:]}\n')
print(f'The b[1:2,0:1] using numpy   : \n\n{b[1:2,0:1]}\n')
print(f'The b[1:3,0:2] using numpy   : \n\n{b[1:3,0:2]}\n')

The b[0,2] using numpy   : 

3

The b[0,:] using numpy   : 

[1 2 3]

The b[1,:] using numpy   : 

[4 5 6]

The b[1:2,0:1] using numpy   : 

[[4]]

The b[1:3,0:2] using numpy   : 

[[4 5]
 [7 8]]



## Arithmetic In Numpy Array

In [198]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'The a+b using numpy   : \n\n{a+b}\n')
print(f'The a+10 using numpy  : \n\n{a+10}\n')
print(f'The a-b using numpy   : \n\n{a-b}\n')
print(f'The a*b using numpy   : \n\n{a*b}\n')
print(f'The np.dot(a,b) using numpy   : \n\n{a+b}\n')
print(f'The np.transpose(a) using numpy   : \n\n{np.dot(a,b)}\n')
print(f'The np.transpose(b) using numpy   : \n\n{np.transpose(b)}\n')
print(f'The np.cross(a,b) using numpy   : \n\n{np.cross(a,b)}\n')

The a+b using numpy   : 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

The a+10 using numpy  : 

[[11 12 13]
 [14 15 16]
 [17 18 19]]

The a-b using numpy   : 

[[0 0 0]
 [0 0 0]
 [0 0 0]]

The a*b using numpy   : 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

The np.dot(a,b) using numpy   : 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

The np.transpose(a) using numpy   : 

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

The np.transpose(b) using numpy   : 

[[1 4 7]
 [2 5 8]
 [3 6 9]]

The np.cross(a,b) using numpy   : 

[[0 0 0]
 [0 0 0]
 [0 0 0]]



## Scientific Calculations

In [201]:
print(f'The np.sin(a) using numpy   : \n\n{np.sin(a)}\n')
print(f'The np.exp(a) using numpy   : \n\n{np.exp(a)}\n')
print(f'The np.log(a) using numpy   : \n\n{np.log(a)}\n')
print(f'The np.abs(a) using numpy   : \n\n{np.abs(a)}\n')

The np.sin(a) using numpy   : 

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

The np.exp(a) using numpy   : 

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

The np.log(a) using numpy   : 

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

The np.abs(a) using numpy   : 

[[1 2 3]
 [4 5 6]
 [7 8 9]]



### Random Uniform

In [205]:
c=np.random.uniform(size=4).reshape(2,2)
print(c)

[[0.64541849 0.99004105]
 [0.81919061 0.521711  ]]
