### Refer: https://numpy.org/doc/2.1/index.html

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [3]:
a = np.array([10,20,30])
print(a)

[10 20 30]


In [5]:
b = np.array([[1,2,3],[10,20,30]])
print(b)

[[ 1  2  3]
 [10 20 30]]


In [6]:
b[0]

array([1, 2, 3])

In [7]:
b[1][1]

20

In [8]:
np.__version__

'1.26.4'

In [9]:
type(b)

numpy.ndarray


### np.arange(start, end, step)

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(5,dtype=float)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.arange(-3, 3, 0.5, dtype=int)


array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

### np.linspace
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

In [38]:
np.linspace(2, 3, num=6)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

## np.eye: identity matrix


In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## np.diag


In [28]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
np.diag([1,2,3],2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
x = np.array([[1,2,3],[14,5,6],[9,10,11]])
np.diag(x)

array([ 1,  5, 11])

## np.vander

In [33]:
y=np.vander([1,2,3,4])
print(y)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [37]:
y=np.vander([1,2,3,4],2)
print(y)
print(y[2][0])

[[1 1]
 [2 1]
 [3 1]
 [4 1]]
3


In [48]:
np.vander(np.linspace(2, 3, num=3))

array([[4.  , 2.  , 1.  ],
       [6.25, 2.5 , 1.  ],
       [9.  , 3.  , 1.  ]])

## 3 Dimension array in numpy

### np.zeros & np.ones

In [5]:
np.zeros(2)

array([0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
np.ones(2)

array([1., 1.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [17]:
from numpy.random import default_rng
default_rng(50).random((2,3))

array([[0.78742269, 0.83366933, 0.54790446],
       [0.9734491 , 0.23683356, 0.64692334]])

### Numpy Indices

In [21]:
np.indices((2,3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [22]:
np.indices((4,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Numpy slicing and copy

In [38]:
a= np.array([1,2,3,4,5,6])
type(a)
print(a)

[1 2 3 4 5 6]


In [39]:
b=a[:2]
print(b)

[1 2]


In [41]:
b+=1


In [42]:
print(b)
print(a)

[3 4]
[3 4 3 4 5 6]


In [43]:
x=np.array([1,2,3,4])
y=x[:2].copy()
y

array([1, 2])

In [44]:
y+=1

In [45]:
print(x)
print(y)

[1 2 3 4]
[2 3]


### Numpy block

In [46]:
A=np.ones((2,2))
B=np.eye(2,2)
C=np.zeros((2,2))
D=np.diag((-3,-4))
newMat = np.block([[A,B],[C,D]])
print(newMat)

[[ 1.  1.  1.  0.]
 [ 1.  1.  0.  1.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0. -4.]]
